sudo: required
services:
  - docker

script:
  - CURRENT_VERSION=$(curl -s https://raw.githubusercontent.com/ngovil21/Plex-Cleaner/master/PlexCleaner.py | grep "# Version" | tail -n 1 | sed 's/# Version \(.*\) - .*/\1/g')
  - docker build -t "bentilbrook/plex-cleaner:latest" .
  - docker tag "bentilbrook/plex-cleaner:latest" "bentilbrook/plex-cleaner:$CURRENT_VERSION"

after_script:
  - ./tests/test-parameters-forwarding.sh
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push "bentilbrook/plex-cleaner:latest"
  - docker push "bentilbrook/plex-cleaner:$CURRENT_VERSION"